### ISSUE TITLE
Search functionality 

### ISSUE THREAD

**Issue by bumbeishvili** [datavis-tech/community#15] opened 2018-02-21 11:51 UTC
It would be good if platform had extensive search & filter functionality  (like blockbuilder.org)

Also, it will be very nice, if user will have possibility to sort results by popularity  (View Count)

**Comment by curran** [comment] 2018-02-22 12:40
Indeed, Search would be a great feature. Thanks for filing this!

**Comment by curran** [comment] 2018-02-22 15:10
Duplicate of #12

**Closed** 2018-04-16 05:57 UTC
